version: '3.9'

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: api-tallos-flix
    ports:
      - 3003:3003
    restart: always
    volumes: 
      - .:/home/node/app
    tty: true
#version: '3.7'

#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    entrypoint: sh ./.docker/entrypoint.sh
#    container_name: api-tallos-flix
#    ports: 
#     - 3003:3003
#    volumes: 
#     - ./:/usr/tallosflix/app