version: '3.9'

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: api-tallos-flix
    ports:
      - 3003:3003
    restart: always
    volumes: 
      - .:/home/node/app
      - /app/node_modules/bcrypt/
    tty: true