#version: '3.9'

#services:
#  app:
#    build: .
#    entrypoint: sh ./.docker/entrypoint.sh
#    container_name: api-tallos-flix
#    ports:
#      - 3003:3003
#    restart: always
#    volumes: 
#      - .:/home/node/app
#      - /app/node_modules/bcrypt/
#    tty: true

version: "3.7"

networks:
  kong-net:
    name: kong-net
    driver: bridge
   

services:

  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    image: api-tallosflix/kong-service:latest
    environment:
      PORT: ":3003"
      CONTENT: "<h1>Api tallosflix</h1>"
    networks:
      - kong-net
    ports:
      - 3003:3003
    volumes: 
      - .:/home/node/app
      - /app/node_modules/bcrypt/
    tty: true